name: Build and Push Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
        branch:
          description: 'Branch to use'
          required: true
          default: 'main'

env:
  PACKER_VERSION: "latest"
  QCOW2_IMG: ${{ vars.REGISTRY }}/${{ vars.REPO }}/vjailbreak
  UI_IMG: ${{ vars.REGISTRY }}/${{ vars.REPO }}/vjailbreak-ui
  V2V_IMG: ${{ vars.REGISTRY }}/${{ vars.REPO }}/vjailbreak-v2v-helper
  CONTROLLER_IMG: ${{ vars.REGISTRY }}/${{ vars.REPO }}/vjailbreak-controller

jobs:
  build-containers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set environment variables for images
      run: |
        # Get the branch name, remove 'refs/heads/' from github.ref
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
        GIT_SHA=$(echo "$(git rev-parse --short HEAD)")
        GIT_BRANCH=$(echo "$(git rev-parse --abbrev-ref HEAD)")
        # if its a release event bump the version and use that as tag
        if [[ "${{ github.event_name }}" == "release" ]]; then
          # In case of release event the tag will be the next version
          # build version will be the same as tag
          TAG=${{ github.event.release.tag_name }}
          BUILD_VERSION=${TAG}
        else
          BUILD_VERSION=${{ github.run_number }}
          # build release version as version-branch-sha
          VERSION=${BUILD_VERSION}-${GIT_BRANCH}-${GIT_SHA}
          # Since this is a merge or pull-request 
          # use the TAG as the version
          TAG=${VERSION}
        fi

        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "TAG=${TAG}" >> $GITHUB_ENV

        echo "QCOW2_IMG=${{ env.QCOW2_IMG }}:$TAG" >> $GITHUB_ENV
        echo "UI_IMG=${{ env.UI_IMG }}:$TAG" >> $GITHUB_ENV
        echo "V2V_IMG=${{ env.V2V_IMG }}:$TAG" >> $GITHUB_ENV
        echo "CONTROLLER_IMG=${{ env.CONTROLLER_IMG }}:$TAG" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.QUAY_ROBOT_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

    - name: Check Release Condition
      id: check_release
      run: |
        RELEASE_FOUND="false"
        
        # Check if it's a release event
        if [[ "${{ github.event_name }}" == "release" ]]; then
          RELEASE_FOUND="true"
        fi
        
        # Check if PR title contains 'release'
        if [[ "${{ github.event.pull_request.title }}" == *"release"* ]]; then
          RELEASE_FOUND="true"
        fi
        
        # Check if it's a manual trigger from main branch
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          RELEASE_FOUND="true"
        fi
        
        echo "release_found=${RELEASE_FOUND}" >> $GITHUB_ENV

    # Parallel steps to build images and create deploy folder
    - name: Prepare build directories
      run: mkdir -p image_builder/deploy

    # Start parallel build and setup steps
    - name: Prepare for QCOW2 build
      if: env.release_found == 'true'
      run: |
        # Enable KVM group perms
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        
        # Set up QEMU
        sudo apt-get update && sudo apt-get install qemu-system qemu-utils -y
        
        # Setup oras
        curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
        mkdir -p oras-install/
        tar -zxf oras_1.1.0_linux_amd64.tar.gz -C oras-install/
        sudo mv oras-install/oras /usr/local/bin/
        rm -rf oras_1.1.0_linux_amd64.tar.gz oras-install/
        
        # Download base image
        oras pull quay.io/platform9/vjailbreak:base-v0.1.4
      &

    # Run UI build in background
    - name: Build and push UI image
      run: make ui &

    # Run v2v-helper build in background
    - name: Build and push v2v-helper image
      run: make v2v-helper &

    # Create deploy folder in background
    - name: Prepare deploy manifests
      run: |
        # Substitue image tags in manifests
        mkdir -p image_builder/deploy
        
        # Setup Go for controller manifests
        if ! command -v go &> /dev/null; then
          wget https://go.dev/dl/go1.22.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
        fi
        
        # Generate controller manifests
        make -C ./k8s/migration/ build-installer
        cp ./k8s/migration/dist/install.yaml image_builder/deploy/00controller.yaml
        cp -r ./k8s/kube-prometheus image_builder/deploy/
      &

    # Wait for parallel processes to complete
    - name: Wait for parallel processes
      run: wait

    # Once v2v-helper is built, start controller build
    - name: Build and push controller image
      run: make -o v2v-helper vjail-controller

    # Complete the deploy manifests substitution after builds are done
    - name: Substitute image tags in manifests
      uses: danielr1996/envsubst-action@1.0.0
      with:
        input: ./ui/deploy/ui.yaml
        output: ./image_builder/deploy/01ui.yaml

    # Setup Packer and build QCOW2 if this is a release
    - name: Setup Packer
      if: env.release_found == 'true'
      uses: hashicorp/setup-packer@main
      with:
        version: ${{ env.PACKER_VERSION }}

    - name: Run Packer Init and Validate
      if: env.release_found == 'true'
      run: |
        packer init ./image_builder/vjailbreak-image.pkr.hcl
        packer validate ./image_builder/vjailbreak-image.pkr.hcl

    - name: Run Packer Build
      if: env.release_found == 'true'
      run: |
        mkdir -p vjailbreak_qcow2
        PACKER_LOG=1 packer build ./image_builder/vjailbreak-image.pkr.hcl

    - name: Upload vjailbreak qcow2 to quay
      if: env.release_found == 'true'
      run: |
        oras push ${{ env.QCOW2_IMG }} \
        --artifact-type="application/qcow2" \
        ./vjailbreak_qcow2/vjailbreak-image.qcow2
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vjailbreak-yamls
        path: |
          image_builder/deploy/00controller.yaml
          image_builder/deploy/01ui.yaml